apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mckube-writer
  namespace: default
rules:
- apiGroups: ["mcoperator.sdv.com"]
  resources: ["mckubes"]
  verbs: ["get", "list", "watch", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mckube-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: mckube-writer
  apiGroup: rbac.authorization.k8s.io
